name: Publish Projects

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  remove-old-drafts:
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Delete drafts
        uses: hugo19941994/delete-draft-releases@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  pages-js:
    if: success()
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        proj:
          - web-coconut

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2 #https://github.com/actions/checkout
        
      - name: Download build artifacts
        uses: actions/download-artifact@v1
        with:
            name: ${{ matrix.proj }}
            path: release

      - name: Deploy gh-pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: pages
          folder: release
          target-folder: release/${{ matrix.proj }}

  pages-hl:
    if: success()
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - js
          - swf
        proj:
          - async
          - heaps
          - heaps-cubefield
          - hl-tui
          - hxbit
          - hxwebsockets
          - mphx
          - udprotean

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2 #https://github.com/actions/checkout
        
      - name: Download build artifacts
        continue-on-error: true
        id: artifact
        uses: actions/download-artifact@v1
        with:
            name: ${{ matrix.os }} ${{ matrix.proj }}
            path: release
            
      - name: Deploy gh-pages
        if: steps.artifact.conclusion != 'failure'
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: pages
          folder: release
          target-folder: release/${{ matrix.proj }}-${{ matrix.os }} 

  release-cpp:
    if: success()
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: 
          - ubuntu-latest
          - macos-latest
          - windows-latest
        proj:
          - hxraylib

    steps:
      - name: Download build artifacts
        continue-on-error: true
        id: artifact
        uses: actions/download-artifact@v1
        with:
            name: ${{ matrix.os }} ${{ matrix.proj }}
            
      - uses: edgarrc/action-7z@v1
        if: steps.artifact.conclusion != 'failure'
        with:
          args: 7z a -t7z -mx=9 release.7z ./

      - name: Check for haxelib
        if: steps.artifact.conclusion != 'failure'
        run: echo '::set-output name=haxelib::'`(test -f haxelib.json && echo "true") || echo "false"`
        id: check

      - uses: EndBug/version-check@v1
        continue-on-error: true
        if: steps.artifact.conclusion != 'failure' && steps.check.outputs.haxelib
        id: version
        with:
          file-name: haxelib.json
          diff-search: true
    
      - name: Create Release
        if: steps.artifact.conclusion != 'failure' && (steps.check.outputs.haxelib != 'true' || steps.version.conclusion == 'failure')
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ matrix.proj }} Release-${{ matrix.os }}
          draft: true
          prerelease: true

      - name: Create Haxelib Release
        if: steps.artifact.conclusion != 'failure' && steps.check.outputs.haxelib == 'true' && steps.version.conclusion != 'failure' && steps.version.outputs.changed
        id: create_hl_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.check.outputs.version }}
          release_name: ${{ matrix.proj }} Release-${{ matrix.os }} ${{ steps.version.outputs.version }}
          draft: true
          prerelease: true

      - name: Upload Release Asset
        if: steps.artifact.conclusion != 'failure' && (steps.check.outputs.haxelib != 'true' || steps.version.conclusion == 'failure')
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
        # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. 
        # See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release.7z
          asset_name: release.7z
          asset_content_type: application/x-7z-compressed

      - name: Upload Haxelib Release Asset
        if: steps.artifact.conclusion != 'failure' && steps.check.outputs.haxelib == 'true' && steps.version.conclusion != 'failure' && steps.version.outputs.changed
        id: upload-hl-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
        # This pulls from the CREATE HL RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. 
        # See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          upload_url: ${{ steps.create_hl_release.outputs.upload_url }}
          asset_path: ./release.7z
          asset_name: release.7z
          asset_content_type: application/x-7z-compressed

      - name: Clone repo for publishing
        if: steps.artifact.conclusion != 'failure' && steps.check.outputs.haxelib == 'true' && steps.version.conclusion != 'failure' && steps.version.outputs.changed
        uses: actions/checkout@v2

      - name: Setup publishing haxelib
        if: steps.artifact.conclusion != 'failure' && steps.check.outputs.haxelib == 'true' && steps.version.conclusion != 'failure' && steps.version.outputs.changed
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5

      - name: Publish to haxelib
        if: steps.artifact.conclusion != 'failure' && steps.check.outputs.haxelib == 'true' && steps.version.conclusion != 'failure' && steps.version.outputs.changed
        shell: bash
        run: |
          cd ${{ matrix.proj }}
          haxe -version
          haxelib submit . ${{ secrets.HAXELIB_PASSWORD }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-hl:
    if: success()
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: 
          - linux
          - windows
          - directx
          - js
          - swf
        proj:
          - async
          - heaps
          - heaps-cubefield
          - hl-tui
          - hxbit
          - hxwebsockets
          - mphx
          - udprotean

    steps:
      - name: Download build artifacts
        continue-on-error: true
        id: artifact
        uses: actions/download-artifact@v1
        with:
            name: ${{ matrix.os }} ${{ matrix.proj }}
            
      - uses: edgarrc/action-7z@v1
        if: steps.artifact.conclusion != 'failure'
        with:
          args: 7z a -t7z -mx=9 release.7z ./

      - name: Check for haxelib
        if: steps.artifact.conclusion != 'failure'
        run: echo '::set-output name=haxelib::'`(test -f haxelib.json && echo "true") || echo "false"`
        id: check

      - uses: EndBug/version-check@v1
        continue-on-error: true
        if: steps.artifact.conclusion != 'failure' && steps.check.outputs.haxelib == 'true'
        id: version
        with:
          file-name: haxelib.json
          diff-search: true
    
      - name: Create Release
        if: steps.artifact.conclusion != 'failure' && (steps.check.outputs.haxelib != 'true' || steps.version.conclusion == 'failure')
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ matrix.proj }} Release-${{ matrix.os }}
          draft: true
          prerelease: true

      - name: Create Haxelib Release
        if: steps.artifact.conclusion != 'failure' && steps.check.outputs.haxelib == 'true' && steps.version.outputs.changed
        id: create_hl_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.check.outputs.version }}
          release_name: ${{ matrix.proj }} Release-${{ matrix.os }} ${{ steps.version.outputs.version }}
          draft: true
          prerelease: true

      - name: Upload Release Asset
        if: steps.artifact.conclusion != 'failure' && (steps.check.outputs.haxelib != 'true' || steps.version.conclusion == 'failure')
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
        # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. 
        # See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release.7z
          asset_name: release.7z
          asset_content_type: application/x-7z-compressed

      - name: Upload Haxelib Release Asset
        if: steps.artifact.conclusion != 'failure' && steps.check.outputs.haxelib == 'true' && steps.version.conclusion != 'failure' && steps.version.outputs.changed
        id: upload-hl-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
        # This pulls from the CREATE HL RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. 
        # See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          upload_url: ${{ steps.create_hl_release.outputs.upload_url }}
          asset_path: ./release.7z
          asset_name: release.7z
          asset_content_type: application/x-7z-compressed

      - name: Clone repo for publishing
        if: steps.artifact.conclusion != 'failure' && steps.check.outputs.haxelib == 'true' && steps.version.conclusion != 'failure' && steps.version.outputs.changed
        uses: actions/checkout@v2

      - name: Setup publishing haxelib
        if: steps.artifact.conclusion != 'failure' && steps.check.outputs.haxelib == 'true' && steps.version.conclusion != 'failure' && steps.version.outputs.changed
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5

      - name: Publish to haxelib
        if: steps.artifact.conclusion != 'failure' && steps.check.outputs.haxelib == 'true' && steps.version.conclusion != 'failure' && steps.version.outputs.changed
        shell: bash
        run: |
          cd ${{ matrix.proj }}
          haxe -version
          haxelib submit . ${{ secrets.HAXELIB_PASSWORD }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-js:
    if: success()
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        proj:
          - web-coconut

    steps:
      - name: Download build artifacts
        continue-on-error: true
        id: artifact
        uses: actions/download-artifact@v1
        with:
            name: ${{ matrix.proj }}
            
      - uses: edgarrc/action-7z@v1
        if: steps.artifact.conclusion != 'failure'
        with:
          args: 7z a -t7z -mx=9 release.7z ./

      - name: Check for haxelib
        if: steps.artifact.conclusion != 'failure'
        run: echo '::set-output name=haxelib::'`(test -f haxelib.json && echo "true") || echo "false"`
        id: check

      - uses: EndBug/version-check@v1
        continue-on-error: true
        if: steps.artifact.conclusion != 'failure' && steps.check.outputs.haxelib
        id: version
        with:
          file-name: haxelib.json
          diff-search: true
    
      - name: Create Release
        if: steps.artifact.conclusion != 'failure' && (steps.check.outputs.haxelib != 'true' || steps.version.conclusion == 'failure')
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ matrix.proj }} pages
          draft: true
          prerelease: true

      - name: Create Haxelib Release
        if: steps.artifact.conclusion != 'failure' && steps.check.outputs.haxelib == 'true' && steps.version.conclusion != 'failure' && steps.version.outputs.changed
        id: create_hl_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.check.outputs.version }}
          release_name: ${{ matrix.proj }} pages ${{ steps.version.outputs.version }}
          draft: true
          prerelease: true

      - name: Upload Release Asset
        if: steps.artifact.conclusion != 'failure' && (steps.check.outputs.haxelib != 'true' || steps.version.conclusion == 'failure')
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
        # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. 
        # See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release.7z
          asset_name: release.7z
          asset_content_type: application/x-7z-compressed

      - name: Upload Haxelib Release Asset
        if: steps.artifact.conclusion != 'failure' && steps.check.outputs.haxelib == 'true' && steps.version.conclusion != 'failure' && steps.version.outputs.changed
        id: upload-hl-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
        # This pulls from the CREATE HL RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. 
        # See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          upload_url: ${{ steps.create_hl_release.outputs.upload_url }}
          asset_path: ./release.7z
          asset_name: release.7z
          asset_content_type: application/x-7z-compressed

      - name: Clone repo for publishing
        if: steps.artifact.conclusion != 'failure' && steps.check.outputs.haxelib == 'true' && steps.version.conclusion != 'failure' && steps.version.outputs.changed
        uses: actions/checkout@v2

      - name: Setup publishing haxelib
        if: steps.artifact.conclusion != 'failure' && steps.check.outputs.haxelib == 'true' && steps.version.conclusion != 'failure' && steps.version.outputs.changed
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5

      - name: Publish to haxelib
        if: steps.artifact.conclusion != 'failure' && steps.check.outputs.haxelib == 'true' && steps.version.conclusion != 'failure' && steps.version.outputs.changed
        shell: bash
        run: |
          cd ${{ matrix.proj }}
          haxe -version
          haxelib submit . ${{ secrets.HAXELIB_PASSWORD }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
